version: "1"
context:
  active-host: "wz605.us1.dbt.com"
  active-project: "70471823470026"
projects:
  - project-name: "Analytics"
    project-id: "70471823470026"
    account-name: "Tiger Analytics"
    account-id: "70471823461998"
    account-host: "wz605.us1.dbt.com"
    token-name: "cloud-cli-4e12"
    token-value: "dbtu_AB-9x34C42bCrDabqb298FGuw67VCNqxyt-d4CHcu1frJcxaMk"

# dbt_project.yml
name:
version:
...
dbt-cloud:
    project-id: 70471823470026